version: '2'

services:
  app:
    image: 'library-readers-img'
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_LIQUIBASE_LIQUIBASE-SCHEMA=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_TOKEN_SECRET=jwtappdemo
      - JWT_TOKEN_EXPIRED=3600000

  postgres:
    image: 'postgres:14.5'
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SCHEMA=postgres